Implement inotify file close events
gorakhargosh/watchdog pull request #690
Opened 2020-10-07 10:13 UTC by lukassup

2020-10-08 13:52 UTC, BoboTiG commented
Hello @lukassup,

Thanks a lot for the patch!

Do you mind adding a line in https://github.com/gorakhargosh/watchdog/blob/master/changelog.rst and a test? It would be perfect :)

2020-10-08 13:54 UTC, BoboTiG commented
Should we make a difference between "write" and "nowrite" events? The later should not trigger a `DirModifiedEvent` maybe?

2020-10-08 16:22 UTC, BoboTiG requested changes

2020-10-08 16:22 UTC, BoboTiG commented on changelog.rst
> +- [inotify] Add events for IN_WRITE_CLOSE and IN_NOWRITE_CLOSE (`#690 <https://github.com/gorakhargosh/watchdog/pull/690>`)
In fact, this is going into v0.10.4, no need for a new version :)

2020-10-08 16:22 UTC, BoboTiG commented on changelog.rst
> +- [inotify] Add events for IN_WRITE_CLOSE and IN_NOWRITE_CLOSE (`#690 <https://github.com/gorakhargosh/watchdog/pull/690>`)
Also add youself in the line (in 0.10.4) "Thanks to our beloved contributors: ...".

2020-10-08 16:32 UTC, lukassup commented
Thanks! Will do more extensive testing a bit later.

2020-10-08 16:43 UTC, BoboTiG commented
Thanks to you 👍 
Let me know when you are ready for another review.

2021-01-15 09:23 UTC, BoboTiG commented
Superseded by #747. Thanks a lot @lukassup for the initial patch (you've been credited correctly) 💪

2021-01-15 09:23 UTC, closed without merging